import type { KnowledgeBundle } from './contracts.ts'

const observedAt = '2026-08-18T03:00:00+08:00'
const piSource = 'earendil-works/pi-ai@0.82.1'
const piCommit = 'b4f293684bba718d59cc1157679bcf6157b3a7f5'

export const BASELINE_KNOWLEDGE_BUNDLE = {
  schemaVersion: 1,
  bundleId: 'dshelm-v0.3-baseline-2026-08-18',
  generatedAt: observedAt,
  records: [
    {
      id: 'deepseek/deepseek-v4-flash',
      provider: 'deepseek',
      model: 'deepseek-v4-flash',
      displayName: 'DeepSeek V4 Flash',
      hard: {
        runtimeReady: true,
        protocol: 'deepseek-chat',
        reasoningEfforts: ['off', 'high', 'max'],
        streaming: true,
        authMethods: ['api-key'],
      },
      soft: [],
      adaptationHints: [],
      evidence: [{
        id: 'dsh-keyless-exact-model-flash',
        layer: 'runtime',
        source: 'DSHelm keyless exact-model contract test',
        sourceUrl: 'https://github.com/Altairpaca/dshelm/blob/5df586d3f01999773b9f54d476874f2a0f3edc54/packages/dsh/tests/keyless-vertical-slice.test.ts',
        sourceCommit: '5df586d3f01999773b9f54d476874f2a0f3edc54',
        observedAt,
        subject: 'deepseek/deepseek-v4-flash',
        claimType: 'runtimeReady',
        value: true,
        confidence: 0.8,
        staleAfterDays: 14,
      }],
    },
    {
      id: 'deepseek/deepseek-v4-pro',
      provider: 'deepseek',
      model: 'deepseek-v4-pro',
      displayName: 'DeepSeek V4 Pro',
      hard: {
        runtimeReady: true,
        protocol: 'deepseek-chat',
        reasoningEfforts: ['off', 'high', 'max'],
        streaming: true,
        authMethods: ['api-key'],
      },
      soft: [],
      adaptationHints: [],
      evidence: [{
        id: 'dsh-keyless-exact-model-pro',
        layer: 'runtime',
        source: 'DSHelm keyless exact-model contract test',
        sourceUrl: 'https://github.com/Altairpaca/dshelm/blob/5df586d3f01999773b9f54d476874f2a0f3edc54/packages/dsh/tests/keyless-vertical-slice.test.ts',
        sourceCommit: '5df586d3f01999773b9f54d476874f2a0f3edc54',
        observedAt,
        subject: 'deepseek/deepseek-v4-pro',
        claimType: 'runtimeReady',
        value: true,
        confidence: 0.8,
        staleAfterDays: 14,
      }],
    },
    {
      id: 'openai/gpt-5-mini',
      provider: 'openai',
      model: 'gpt-5-mini',
      displayName: 'GPT-5 mini',
      hard: { protocol: 'openai-responses', streaming: true, authMethods: ['api-key'] },
      soft: [],
      adaptationHints: [],
      evidence: [{
        id: 'pi-openai-gpt5-mini-catalog',
        layer: 'community',
        source: piSource,
        sourceUrl: 'https://github.com/earendil-works/pi/blob/b4f293684bba718d59cc1157679bcf6157b3a7f5/packages/ai/README.md',
        sourceCommit: piCommit,
        observedAt,
        subject: 'openai/gpt-5-mini',
        claimType: 'protocol',
        value: 'openai-responses',
        confidence: 0.65,
        staleAfterDays: 30,
      }],
    },
    {
      id: 'anthropic/claude-sonnet-4-5',
      provider: 'anthropic',
      model: 'claude-sonnet-4-5',
      displayName: 'Claude Sonnet 4.5',
      hard: { protocol: 'anthropic-messages', streaming: true, authMethods: ['api-key', 'library-oauth'] },
      soft: [],
      adaptationHints: [],
      evidence: [{
        id: 'pi-anthropic-oauth-and-catalog',
        layer: 'community',
        source: piSource,
        sourceUrl: 'https://github.com/earendil-works/pi/blob/b4f293684bba718d59cc1157679bcf6157b3a7f5/packages/ai/src/providers/anthropic.ts',
        sourceCommit: piCommit,
        observedAt,
        subject: 'anthropic/claude-sonnet-4-5',
        claimType: 'authMethods',
        value: ['api-key', 'library-oauth'],
        confidence: 0.65,
        staleAfterDays: 30,
      }],
    },
    {
      id: 'local/qwen3-30b',
      provider: 'local',
      model: 'qwen3-30b',
      displayName: 'Qwen3 30B (local example)',
      hard: { protocol: 'openai-completions', localDeployment: true, openWeights: true, authMethods: ['local'] },
      soft: [],
      adaptationHints: [],
      evidence: [{
        id: 'pi-local-qwen-example',
        layer: 'community',
        source: piSource,
        sourceUrl: 'https://github.com/earendil-works/pi/blob/b4f293684bba718d59cc1157679bcf6157b3a7f5/packages/ai/README.md',
        sourceCommit: piCommit,
        observedAt,
        subject: 'local/qwen3-30b',
        claimType: 'localDeployment',
        value: true,
        confidence: 0.55,
        staleAfterDays: 90,
      }],
    },
    {
      id: 'local/gpt-oss-20b',
      provider: 'local',
      model: 'gpt-oss:20b',
      displayName: 'gpt-oss 20B (local example)',
      hard: { protocol: 'openai-completions', localDeployment: true, openWeights: true, authMethods: ['local'] },
      soft: [],
      adaptationHints: [],
      evidence: [{
        id: 'pi-gpt-oss-local-example',
        layer: 'community',
        source: piSource,
        sourceUrl: 'https://github.com/earendil-works/pi/blob/b4f293684bba718d59cc1157679bcf6157b3a7f5/packages/ai/README.md',
        sourceCommit: piCommit,
        observedAt,
        subject: 'local/gpt-oss:20b',
        claimType: 'openWeights',
        value: true,
        confidence: 0.55,
        staleAfterDays: 90,
      }],
    },
  ],
} satisfies KnowledgeBundle
